version: '3'

services:
  techday:
    build: .
    container_name: database_test
    restart: always
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin  
        POSTGRES_DB: videogames  
    ports:
      - "5432:5432"